# Generated by Django 4.2.8 on 2024-02-13 04:37

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('reminder_days', models.IntegerField(blank=True, default=7, null=True)),
                ('tag', models.CharField(default='Birthday', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text')),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Diary Entries',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='main', max_length=30)),
                ('dog_diary_days', models.IntegerField(default=200)),
                ('wordles_to_do', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='MaxTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('max', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TennisMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_A', models.CharField(max_length=30, null=True)),
                ('player_B', models.CharField(max_length=30, null=True)),
                ('score_A', models.IntegerField(blank=True, default=0, null=True)),
                ('score_B', models.IntegerField(blank=True, default=0, null=True)),
                ('match_date', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('king_max', models.IntegerField(blank=True, null=True)),
                ('queen_max', models.IntegerField(blank=True, null=True)),
                ('warden_max', models.IntegerField(blank=True, null=True)),
                ('champ_max', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tide_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wordle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5, null=True)),
                ('guess_1', models.CharField(max_length=5, null=True)),
                ('guess_2', models.CharField(max_length=5, null=True)),
                ('guess_3', models.CharField(max_length=5, null=True)),
                ('guess_4', models.CharField(max_length=5, null=True)),
                ('guess_5', models.CharField(max_length=5, null=True)),
                ('guess_6', models.CharField(max_length=5, null=True)),
                ('date', models.DateField(null=True)),
                ('last_reviewed', models.DateField(default=None, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True)),
                ('precis', models.CharField(max_length=30, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tide_date')),
            ],
        ),
        migrations.CreateModel(
            name='TimerElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.timer')),
            ],
        ),
        migrations.CreateModel(
            name='TennisSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_no', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tennismatch')),
            ],
        ),
        migrations.CreateModel(
            name='TennisGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_no', models.IntegerField(blank=True, null=True)),
                ('score_A', models.IntegerField(blank=True, null=True)),
                ('score_B', models.IntegerField(blank=True, null=True)),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tennisset')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('buy', models.BooleanField(null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('last_edited', models.DateField(auto_now=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('king', models.IntegerField(blank=True, null=True)),
                ('queen', models.IntegerField(blank=True, null=True)),
                ('warden', models.IntegerField(blank=True, null=True)),
                ('champ', models.IntegerField(blank=True, null=True)),
                ('th', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.th')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, null=True)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text')),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly')], null=True)),
                ('note_date', models.DateField(null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.note')),
            ],
        ),
        migrations.CreateModel(
            name='New_Tide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True)),
                ('height', models.FloatField()),
                ('type', models.CharField(max_length=10, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tide_date')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('owners', models.TextField(blank=True, null=True)),
                ('owners_number', models.TextField(blank=True, null=True)),
                ('notes', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text')),
                ('approved', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Limited', 'Limited')], default='Yes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('owners_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.note')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dog')),
            ],
        ),
    ]
