# Generated by Django 4.2.8 on 2023-12-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_event_diary_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
