# Generated by Django 4.2.8 on 2024-01-04 03:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_player_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
