# Generated by Django 4.2.8 on 2023-12-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_text_diary_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='event',
            new_name='text',
        ),
    ]
