# Generated by Django 4.2.8 on 2023-12-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_note_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='reminder_days',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
