# Generated by Django 4.2.8 on 2024-01-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_event_dog_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
