# Generated by Django 4.2.8 on 2024-01-02 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_quote_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('king_max', models.IntegerField(blank=True, null=True)),
                ('queen_max', models.IntegerField(blank=True, null=True)),
                ('warden_max', models.IntegerField(blank=True, null=True)),
                ('champ_max', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': 'Diary Entries'},
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('king_max', models.IntegerField(blank=True, null=True)),
                ('queen_max', models.IntegerField(blank=True, null=True)),
                ('warden_max', models.IntegerField(blank=True, null=True)),
                ('champ_max', models.IntegerField(blank=True, null=True)),
                ('th', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.th')),
            ],
        ),
    ]
