# Generated by Django 4.2.8 on 2024-01-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_th_alter_category_options_alter_diary_options_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='champ_max',
            new_name='champ',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='king_max',
            new_name='king',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='queen_max',
            new_name='queen',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='warden_max',
            new_name='warden',
        ),
    ]
