# Generated by Django 4.2.8 on 2024-01-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_champ_max_player_champ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
