# Generated by Django 4.2.8 on 2024-01-04 08:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_note_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
