# Generated by Django 4.2.8 on 2024-01-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_shopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='buy',
            field=models.BooleanField(null=True),
        ),
    ]
