# Generated by Django 4.2.8 on 2024-01-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_timer_timerelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerelement',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
