# Generated by Django 4.2.8 on 2024-01-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_timerelement_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tide_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
