# Generated by Django 4.2.8 on 2024-01-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='tag',
            field=models.CharField(default='Birthday', max_length=255),
        ),
    ]
