# Generated by Django 4.2.8 on 2024-01-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_birthday_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('max', models.IntegerField(null=True)),
            ],
        ),
    ]
