# Generated by Django 4.2.8 on 2024-01-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_maxtemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_date',
            field=models.DateField(null=True),
        ),
    ]
