# Generated by Django 4.2.8 on 2024-01-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_wordle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='owners_link',
            field=models.ForeignKey(limit_choices_to={'category': 'people'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.note'),
        ),
    ]
