# Generated by Django 4.2.8 on 2024-01-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_dog_owners_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
