# Generated by Django 4.2.8 on 2024-01-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_shopping_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='last_edited',
            field=models.DateField(auto_now=True),
        ),
    ]
