# Generated by Django 4.2.8 on 2024-01-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_shopping_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordle',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
