# Generated by Django 4.2.8 on 2024-01-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_wordle_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordle',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
