# Generated by Django 4.2.8 on 2024-01-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_wordle_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='owners_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.note'),
        ),
    ]
