# Generated by Django 4.2.8 on 2024-01-17 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_tennisgamescore_tennisplayer_tennissetscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='TennisGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField(null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('player_A', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_A', to='app.tennisplayer')),
                ('player_B', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_B', to='app.tennisplayer')),
            ],
        ),
        migrations.AddField(
            model_name='tennisgamescore',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tennisgame'),
        ),
        migrations.AddField(
            model_name='tennissetscore',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tennisgame'),
        ),
    ]
