# Generated by Django 4.2.8 on 2024-01-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_tennisgame_score_a_tennisgame_score_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennisgame',
            name='game_score_A',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tennisgame',
            name='game_score_B',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tennisgame',
            name='score_A',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tennisgame',
            name='score_B',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
