# Generated by Django 4.2.8 on 2024-01-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_tennismatch_tennisset_remove_tennissetscore_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennisgame',
            name='game_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
