# Generated by Django 4.2.8 on 2024-01-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_tennisgame_game_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='main', max_length=30)),
                ('dog_diary_days', models.IntegerField(default=200)),
            ],
        ),
    ]
