# Generated by Django 4.2.8 on 2024-01-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='approved',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Limited', 'Limited')], default='Yes'),
        ),
    ]
