# Generated by Django 4.2.8 on 2024-01-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_dog_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordle',
            name='guess_1',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='wordle',
            name='guess_2',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='wordle',
            name='guess_3',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='wordle',
            name='guess_4',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='wordle',
            name='guess_5',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='wordle',
            name='guess_6',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
