# Generated by Django 4.2.8 on 2024-01-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_wordle_guess_1_wordle_guess_2_wordle_guess_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='wordles_to_do',
            field=models.IntegerField(default=3),
        ),
    ]
