# Generated by Django 4.2.8 on 2024-01-27 21:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_general_wordles_to_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
