# Generated by Django 4.2.8 on 2024-01-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_dog_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='owners_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
