# Generated by Django 4.2.8 on 2024-01-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_dog_owners_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tennismatch',
            name='game_date',
        ),
        migrations.AddField(
            model_name='tennismatch',
            name='match_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
