# Generated by Django 4.2.8 on 2024-01-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_remove_tennismatch_game_date_tennismatch_match_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tennismatch',
            name='player_A',
        ),
        migrations.RemoveField(
            model_name='tennismatch',
            name='player_B',
        ),
        migrations.AddField(
            model_name='tennismatch',
            name='player_A_str',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tennismatch',
            name='player_B_str',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
