# Generated by Django 4.2.8 on 2024-01-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_remove_tennismatch_player_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tennismatch',
            old_name='player_A_str',
            new_name='player_A',
        ),
        migrations.RenameField(
            model_name='tennismatch',
            old_name='player_B_str',
            new_name='player_B',
        ),
    ]
