# Generated by Django 4.2.8 on 2024-01-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_rename_player_a_str_tennismatch_player_a_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TennisPlayer',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='date',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='note',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly')], null=True),
        ),
    ]
