# Generated by Django 4.2.8 on 2024-02-09 03:50

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_delete_tennisplayer_rename_date_note_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='notes',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text'),
        ),
    ]
